import type {Express,Request} from 'express';import {randomUUID,createHash} from 'node:crypto';import {z} from 'zod';import {saveAttachment} from './artifacts.js';import {seedEmployee} from './capabilities.js';import {terminal} from './runs.js';import {drainContext} from '../turn.js';import {canonical} from './tools.js';import type {installEmployee} from './routes.js';
/** The native clients and LiveKit worker keep their existing gateway protocol. */
export function installLegacyTasks(app:Express,e:ReturnType<typeof installEmployee>,resolve:(r:Request)=>string|null){
 const ingesting=new Map<string,Promise<any>>();
 const ingest=(owner:string,body:any,key:string):Promise<any>=>{
  const mapKey=owner+':'+key;const hash=createHash('sha256').update(canonical(body)).digest('hex');
  const prior=ingesting.get(mapKey);if(prior)return prior.then(()=>ingest(owner,body,key));
  const job=(async()=>{const intakeId=createHash('sha256').update(mapKey).digest('hex'),old=e.db.get(owner,'intake',intakeId);if(old){if(old.hash!==hash)throw Error('Request identifier already used');return e.db.get(owner,'run',old.runId)!;}
   seedEmployee(e.db,owner);const task=z.string().trim().min(1).max(12000).parse(body.messages?.filter((m:any)=>m.role==='user').at(-1)?.content),attachments:string[]=[];
   if(body.image){const image=z.string().max(5*1024*1024).regex(/^[A-Za-z0-9+/=]+$/).parse(body.image);attachments.push((await saveAttachment(e.db,owner,Buffer.from(image,'base64'),'Delegated visual evidence')).id);}
   const notes=drainContext(owner).join('\n').slice(0,4000);const run=e.q.create(owner,{task,context:{source:body.source==='glasses'?'glasses':'phone',attachments,visualDescription:notes}},key);e.db.put(owner,'intake',{id:intakeId,hash,runId:run.id});void e.q.tick();return run;
  })();ingesting.set(mapKey,job);void job.finally(()=>ingesting.delete(mapKey)).catch(()=>{});return job;
 };
 app.post('/v1/chat/completions',async(req,res)=>{const owner=resolve(req);if(!owner){res.sendStatus(401);return;}try{const run=await ingest(owner,req.body,req.header('idempotency-key')??randomUUID());const content='[task started] Briefly acknowledge the assignment. Its verified result will arrive after it finishes.';const envelope={id:run.id,runId:run.id,object:'chat.completion',created:Math.floor(Date.now()/1000),model:'visionclaw',choices:[{index:0,message:{role:'assistant',content},finish_reason:'stop'}]};if(req.body.stream){res.set('Content-Type','text/event-stream');res.end(`data: ${JSON.stringify({...envelope,object:'chat.completion.chunk',choices:[{index:0,delta:{role:'assistant',content},finish_reason:null}]})}\n\ndata: [DONE]\n\n`);}else res.json(envelope);}catch{res.status(400).json({error:{message:'A valid task and attachment are required.'}});}});
 app.post('/browse/start',(req,res)=>{const owner=resolve(req);if(!owner){res.sendStatus(401);return;}if(!process.env.BROWSER_USE_API_KEY){res.sendStatus(503);return;}try{seedEmployee(e.db,owner);const r=e.q.create(owner,{task:req.body.task,context:{source:'phone'}},req.header('idempotency-key')??randomUUID());e.db.put(owner,'run',{...r,browserTask:true});void e.q.tick();res.json({runId:r.id,liveUrl:null});}catch{res.sendStatus(400);}});
 app.post('/browse/await',(req,res)=>{const owner=resolve(req);if(!owner){res.sendStatus(401);return;}const r=e.db.get(owner,'run',String(req.body.runId));if(!r){res.sendStatus(404);return;}const computer=e.db.list(owner,'computer').find(c=>c.runId===r.id);res.json({runId:r.id,status:r.status,result:terminal.has(r.status)?r.result??r.error??`Task ${r.status}`:null,liveUrl:computer?.liveUrl});});
}
