import {readFileSync} from 'node:fs';import {z} from 'zod';import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';import {ToolGateway} from './tools.js';import {Store} from './db.js';import {quoteSchema,registerSupplier} from './procurement.js';
const schema=z.array(z.object({id:z.string().regex(/^[a-z0-9_]+$/),url:z.string().url(),tokenEnv:z.string().regex(/^[A-Z0-9_]+$/).optional(),owners:z.array(z.string()).min(1),tools:z.record(z.string(),z.object({effect:z.enum(['read','write','communication','destructive','sensitive','computer']),inputSchema:z.record(z.string(),z.unknown())})),checkout:z.object({quote:z.string(),refresh:z.string(),order:z.string()}).optional()}));
export class McpConnections{
 readonly config:z.infer<typeof schema>;readonly error?:string;
 constructor(){try{this.config=process.env.MCP_CONFIG_PATH?schema.parse(JSON.parse(readFileSync(process.env.MCP_CONFIG_PATH,'utf8'))):[];if(this.config.some(c=>new URL(c.url).protocol!=='https:'))throw Error();}catch{this.config=[];this.error='MCP configuration is invalid; other capabilities remain available';}}
 async withClient<T>(id:string,owner:string,fn:(client:Client)=>Promise<T>){const conf=this.config.find(c=>c.id===id);if(!conf||!conf.owners.includes(owner))throw Error('Connection is not authorized');const token=conf.tokenEnv?process.env[conf.tokenEnv]:undefined;if(conf.tokenEnv&&!token)throw Error('Connection credential is missing');const client=new Client({name:'visionclaw',version:'1.0.0'});try{await client.connect(new StreamableHTTPClientTransport(new URL(conf.url),{requestInit:{headers:token?{Authorization:`Bearer ${token}`}:{},signal:AbortSignal.timeout(60_000)}}));return await fn(client);}finally{await client.close().catch(()=>{});}}
 async call(id:string,owner:string,name:string,args:Record<string,unknown>,beforeCommit?:()=>void){return this.withClient(id,owner,async client=>{const list=await client.listTools();const tool=list.tools.find(t=>t.name===name);if(!tool)throw Error('Connected capability is unavailable');z.fromJSONSchema(tool.inputSchema as Parameters<typeof z.fromJSONSchema>[0]).parse(args);beforeCommit?.();const r=await client.callTool({name,arguments:args},undefined,{timeout:60_000});if(r.isError)throw Error('Connected capability failed');if(r.structuredContent)return r.structuredContent;const text=(r.content as any[]).filter(c=>c.type==='text').map(c=>c.text).join('\n');try{return JSON.parse(text);}catch{return {text:text.slice(0,100000)};}});}
 register(t:ToolGateway,db:Store){
 t.register({id:'connections_tools',description:'List authorized tools in a connected system',effect:'read',schema:z.object({connection:z.string()}),run:async(a,c)=>this.withClient(a.connection,c.owner,async client=>{const conf=this.config.find(x=>x.id===a.connection)!;return (await client.listTools()).tools.filter(x=>x.name in conf.tools);})});
 for(const conf of this.config){
  if(conf.checkout&&Object.keys(conf.tools).some(k=>Object.values(conf.checkout!).includes(k)))throw Error('Checkout tools require the exact-quote adapter');
  for(const [name,tool] of Object.entries(conf.tools))t.register({id:`mcp_${conf.id}_${name}`.replace(/[^a-zA-Z0-9_-]/g,'_'),owners:conf.owners,description:`${conf.id}: ${name}`,effect:tool.effect,schema:z.fromJSONSchema(tool.inputSchema),run:async(a,c)=>this.call(conf.id,c.owner,name,a,c.assertAuthorized)});
  if(conf.checkout){const mapping=conf.checkout;registerSupplier(t,db,{quote:async(cartId,owner)=>quoteSchema.parse(await this.call(conf.id,owner,mapping.quote,{items:db.get(owner,'cart',cartId)!.items})),refresh:async(quoteId,owner)=>quoteSchema.parse(await this.call(conf.id,owner,mapping.refresh,{quoteId})),order:async(quoteId,idempotencyKey,owner,beforeCommit)=>await this.call(conf.id,owner,mapping.order,{quoteId,idempotencyKey},beforeCommit) as any},conf.id,conf.owners);}
 }
 }
}
