import {z} from 'zod';import {Store} from './db.js';import {ToolGateway,canonical} from './tools.js';import {providerJson} from './communications.js';
export const offerSchema=z.object({supplier:z.string().min(1),sku:z.string(),product:z.string(),url:z.string().url(),specification:z.string().default(''),quantity:z.number().int().positive().max(1000),unitPrice:z.number().nonnegative(),currency:z.string().length(3),shipping:z.number().nonnegative().nullable().default(null),availability:z.string().default('unconfirmed'),fulfillment:z.string().default('unconfirmed'),observedAt:z.string().datetime(),matchQuality:z.enum(['unverified','candidate','exact']).default('candidate')});
export type Offer=z.infer<typeof offerSchema>;
export function compareOffers(offers:Offer[],currency:string){return offers.filter(o=>o.currency===currency).map(o=>({...o,total:o.shipping===null?null:Math.round((o.unitPrice*o.quantity+o.shipping)*100)/100})).sort((a,b)=>(a.total??Infinity)-(b.total??Infinity));}
export interface ProcurementProvider{search(query:string,quantity:number):Promise<Offer[]>}
export class EbayBrowse implements ProcurementProvider{
 constructor(readonly http:typeof fetch=fetch){}
 async search(query:string,quantity:number){const id=process.env.EBAY_CLIENT_ID,secret=process.env.EBAY_CLIENT_SECRET;if(!id||!secret)throw Error('Supplier search is not connected');const auth=await providerJson('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(id+':'+secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',scope:'https://api.ebay.com/oauth/api_scope'})},this.http);const result=await providerJson('https://api.ebay.com/buy/browse/v1/item_summary/search?'+new URLSearchParams({q:query,limit:'12'}),{headers:{Authorization:`Bearer ${auth.access_token}`,'X-EBAY-C-MARKETPLACE-ID':process.env.EBAY_MARKETPLACE??'EBAY_US'}},this.http);
  return (result.itemSummaries??[]).filter((o:any)=>o.price).map((o:any)=>offerSchema.parse({supplier:'eBay / '+(o.seller?.username??'seller'),sku:o.itemId,product:o.title,url:o.itemWebUrl,quantity,unitPrice:Number(o.price.value),currency:o.price.currency,shipping:o.shippingOptions?.[0]?.shippingCost?Number(o.shippingOptions[0].shippingCost.value):null,availability:'Listed; quantity and compatibility must be verified',fulfillment:o.shippingOptions?.[0]?.maxEstimatedDeliveryDate??'Check supplier',observedAt:new Date().toISOString()}));
 }
}
export function registerProcurement(t:ToolGateway,db:Store,providers:ProcurementProvider[]=[new EbayBrowse()]){
 t.register({id:'products_search',description:'Search products and compare current supplier offers',effect:'read',schema:z.object({description:z.string().min(2).max(500),specification:z.string().max(1000).default(''),quantity:z.number().int().min(1).max(1000).default(1),currency:z.string().length(3).default('USD')}),run:async(a,c)=>{const request=db.create(c.owner,'material',{...a,runId:c.runId});const results=await Promise.allSettled(providers.map(p=>p.search(a.description+' '+a.specification,a.quantity)));const offers=results.flatMap(r=>r.status==='fulfilled'?r.value:[]);if(!offers.length)throw Error('No supplier offers available. Check connections or refine the request.');const saved=offers.map(o=>({...db.create(c.owner,'offer',{...o,requestId:request.id,runId:c.runId}),...o}));return {requestId:request.id,offers:compareOffers(saved,a.currency),partial:results.some(r=>r.status==='rejected'),tax:'Taxes and stock are not confirmed until supplier checkout.'};}});
 t.register({id:'cart_build',description:'Save selected products in a cart for review',effect:'write',schema:z.object({offerIds:z.array(z.string()).min(1).max(30)}),run:async(a,c)=>{const items=a.offerIds.map((id:string)=>db.get(c.owner,'offer',id));if(items.some((x:any)=>!x))throw Error('Offer not found');return db.create(c.owner,'cart',{items,runId:c.runId,status:'draft'});}});
}
export const quoteSchema=z.object({supplier:z.string().min(1),quoteId:z.string().min(1),items:z.array(z.object({sku:z.string(),name:z.string(),quantity:z.number().int().positive(),unitPrice:z.number().nonnegative()})).min(1),subtotal:z.number().nonnegative(),tax:z.number().nonnegative(),fees:z.number().nonnegative(),delivery:z.number().nonnegative(),total:z.number().nonnegative(),currency:z.string().length(3),fulfillment:z.string(),deliveryAddress:z.string(),expiresAt:z.string().datetime()});
export interface SupplierCheckout{quote(cartId:string,owner:string):Promise<z.infer<typeof quoteSchema>>;refresh(quoteId:string,owner:string):Promise<z.infer<typeof quoteSchema>>;order(quoteId:string,key:string,owner:string,beforeCommit?:()=>void):Promise<{orderNumber:string;receiptUrl:string;status:string}>}
export function registerSupplier(t:ToolGateway,db:Store,supplier:SupplierCheckout,connection='supplier',owners?:string[]){const suffix=connection==='supplier'?'':`_${connection}`;
 t.register({id:'purchase_quote'+suffix,owners,description:'Get an exact supplier quote including all costs',effect:'read',schema:z.object({cartId:z.string()}),run:async(a,c)=>{if(!db.get(c.owner,'cart',a.cartId))throw Error('Cart not found');const quote=quoteSchema.parse(await supplier.quote(a.cartId,c.owner));return db.create(c.owner,'quote',{...quote,connection,runId:c.runId});}});
 t.register({id:'purchase_order'+suffix,owners,description:'Place the exact purchase shown for approval',effect:'financial',schema:quoteSchema.extend({id:z.string()}),run:async(a,c)=>{
  const saved=db.get(c.owner,'quote',a.id);if(!saved||saved.connection!==connection)throw Error('Quote not found');const approved=quoteSchema.parse(a);if(canonical(approved)!==canonical(quoteSchema.parse(saved)))throw Error('Quote differs from the supplier record');
  const current=quoteSchema.parse(await supplier.refresh(a.quoteId,c.owner));if(Date.parse(current.expiresAt)<=Date.now()||canonical(current)!==canonical(approved))throw Error('Price, stock or fulfillment changed. Request a new quote and approval.');
  const cents=(n:number)=>Math.round(n*100);if(cents(a.subtotal)+cents(a.tax)+cents(a.fees)+cents(a.delivery)!==cents(a.total)||a.items.reduce((n:number,i:any)=>n+cents(i.unitPrice)*i.quantity,0)!==cents(a.subtotal))throw Error('Supplier total does not reconcile');
  c.assertAuthorized();const receipt=z.object({orderNumber:z.string().min(1),receiptUrl:z.string().url(),status:z.string()}).parse(await supplier.order(a.quoteId,c.actionId,c.owner,c.assertAuthorized));return db.create(c.owner,'order',{...approved,...receipt,runId:c.runId,approvalActionId:c.actionId,connection});
 }});
}
