import express,{type Express,type Request,type Response} from 'express';import {z} from 'zod';import {randomUUID,createHmac,timingSafeEqual} from 'node:crypto';import {unlinkSync,rmSync} from 'node:fs';import rateLimit from 'express-rate-limit';
import {Store} from './db.js';import {RunQueue,type Executor} from './runs.js';import {ToolGateway} from './tools.js';import {HermesProvider,hermesHome,selectRuntime} from './provider.js';import {AnthropicManagedRuntime} from './managed.js';import {seedEmployee,registerLocalTools,memorySchema} from './capabilities.js';import {registerCommunications,contactSchema} from './communications.js';import {registerProcurement,optionalSuppliers} from './procurement.js';import {loadSuppliers} from './suppliers.js';import {McpConnections} from './mcp.js';import {BrowserCapability} from './browser.js';import {session,issueSession,type GrantCheck} from './auth.js';import {saveAttachment} from './artifacts.js';import {databasePath,validateEmployeeConfig} from './config.js';import {redactText} from './redact.js';import {userResources,saveStore} from '../store.js';import {notifyUser,queuePending} from '../notify.js';
export type ResolveUser=(req:Request,token?:string)=>string|null;
const kinds=['run','agent','skill','memory','conversation','message','approval','artifact','contact','communication','material','offer','cart','quote','order','workflow','computer','policy','action','evidence_link'] as const;
export function installEmployee(app:Express,resolve:ResolveUser,validGrant:GrantCheck,executor?:Executor){
 validateEmployeeConfig();const db=new Store(databasePath()),tools=new ToolGateway(db);registerLocalTools(tools,db);registerCommunications(tools,db);const suppliers=()=>loadSuppliers(optionalSuppliers()).adapters;registerProcurement(tools,db,undefined);const mcp=new McpConnections();mcp.register(tools,db);const browser=new BrowserCapability(db);browser.register(tools);
 const runtimes={hermes:new HermesProvider(db,tools),anthropic:new AnthropicManagedRuntime(db,tools)};
 const q=new RunQueue(db,executor??(async(owner,run,signal)=>{
  const profile=db.list(owner,'agent')[0],runtime=selectRuntime(profile,run);db.put(owner,'run',{...db.get(owner,'run',run.id)!,runtime});
  const result=run.browserTask?{result:String((await tools.wait(owner,run.id,'browser_work',{task:run.task},run.id,signal)).text)}:await runtimes[runtime as keyof typeof runtimes].run(owner,run,signal);
  if(!signal.aborted){const u=await userResources(owner);u.recentTasks=[...(u.recentTasks??[]),{ts:new Date().toISOString(),prompt:run.task.slice(0,300),result:result.result.slice(0,500)}].slice(-20);await saveStore();notifyUser(owner,result.result);}
  return result;
 }),Number(process.env.RUN_CAPACITY??2));q.recover();
 const cookie=(req:Request)=>session(db,req,validGrant),cookieUser=(req:Request)=>cookie(req)?.owner??null,current=(req:Request)=>cookieUser(req)??resolve(req);
 app.use((req,res,next)=>{const s=cookie(req);if(s&&!['GET','HEAD','OPTIONS'].includes(req.method)&&!req.path.startsWith('/webhooks/')&&req.header('x-csrf-token')!==s.csrf){res.status(403).json({error:{message:'Please refresh your session before trying again.'}});return;}next();});
 const router=express.Router();router.post('/auth/login',rateLimit({windowMs:60000,limit:10,standardHeaders:true,legacyHeaders:false}),(req,res)=>{const token=z.string().min(1).max(1000).parse(req.body?.token),owner=resolve(req,token);if(!owner){res.status(401).json({error:{message:'Unable to verify that access code.'}});return;}seedEmployee(db,owner);res.json({owner,csrf:issueSession(db,res,owner,token)});});
 router.use((req,res,next)=>{const owner=current(req);if(!owner){res.status(401).json({error:{message:'Sign in to continue.'}});return;}seedEmployee(db,owner);res.locals.owner=owner;res.set('Cache-Control','no-store');next();});router.use(rateLimit({windowMs:60000,limit:240,standardHeaders:true,legacyHeaders:false}));
 router.get('/session',(req,res)=>res.json({owner:res.locals.owner,csrf:cookie(req)?.csrf}));router.post('/auth/logout',(req,res)=>{const s=cookie(req);if(s)db.sql.prepare('DELETE FROM sessions WHERE hash=?').run(s.hash);res.clearCookie('vc_session',{path:'/'}).sendStatus(204);});
 router.get('/state',(_req,res)=>res.json(Object.fromEntries(kinds.map(k=>[k,db.list(res.locals.owner,k).map(({path,base64,...r})=>r)]))));
 router.get('/connections',(_req,res)=>res.json({realtime:!!(process.env.LIVEKIT_URL&&process.env.LIVEKIT_API_KEY),hermes:!!process.env.HERMES_CHECKOUT,anthropic:!!process.env.ANTHROPIC_API_KEY,sms:!!(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM),voice:!!(process.env.RETELL_API_KEY&&process.env.RETELL_FROM&&process.env.RETELL_AGENT_ID),products:suppliers().some(s=>s.configured()),suppliers:suppliers().map(s=>({id:s.id,name:s.name,method:s.method,connected:s.configured(),requires:s.requires})),browser:!!process.env.BROWSER_USE_API_KEY,mcp:mcp.config.filter(c=>c.owners.includes(res.locals.owner)).map(c=>({id:c.id,tools:Object.keys(c.tools)})),mcpError:mcp.error}));
 router.post('/execute',(req,res)=>{const r=q.create(res.locals.owner,req.body,req.header('idempotency-key')??'');res.status(202).json(r);void q.tick();});router.get('/runs/:id',(req,res)=>{const r=db.get(res.locals.owner,'run',String(req.params.id));r?res.json(r):res.sendStatus(404);});
 router.post('/runs/:id/:action',(req,res)=>{if(req.params.action==='cancel'){q.cancel(res.locals.owner,String(req.params.id));void browser.cleanup();}else if(req.params.action==='resume'){q.resume(res.locals.owner,String(req.params.id));void q.tick();}else{res.sendStatus(400);return;}res.sendStatus(204);});
 router.post('/actions/:id/reconcile',(req,res)=>{const a=db.get(res.locals.owner,'action',String(req.params.id));if(!a||!['executing','uncertain'].includes(a.status)){res.sendStatus(404);return;}const text=z.string().min(10).max(4000).parse(req.body.evidence);db.put(res.locals.owner,'action',{...a,status:'completed',result:{ownerReconciled:true,evidence:text}});db.create(res.locals.owner,'artifact',{runId:a.runId,kind:'reconciliation',name:'Owner checked action outcome',text});res.sendStatus(204);});
 router.post('/approvals/:id',(req,res)=>{const id=String(req.params.id),decision=z.enum(['once','deny','always','never']).parse(req.body.decision),a=db.get(res.locals.owner,'approval',id);tools.decide(res.locals.owner,id,decision);if(a?.tool==='ask_user'&&req.body.answer)db.create(res.locals.owner,'answer',{runId:a.runId,question:a.details.question,text:z.string().max(4000).parse(req.body.answer)});res.sendStatus(204);});
 router.put('/agent',(req,res)=>{const old=db.list(res.locals.owner,'agent')[0],v=z.object({name:z.string().min(1).max(80),title:z.string().max(100),instructions:z.string().max(8000),runtime:z.enum(['hermes','anthropic']),provider:z.string().max(80).optional(),model:z.string().max(120).optional(),skills:z.array(z.string()).max(30)}).parse(req.body);if(v.skills.some(id=>!db.get(res.locals.owner,'skill',id)))throw Error('Unknown skill');res.json(db.put(res.locals.owner,'agent',{...old,...v}));});
 router.post('/contacts',(req,res)=>res.status(201).json(db.create(res.locals.owner,'contact',contactSchema.parse(req.body))));router.delete('/contacts/:id',(req,res)=>{db.remove(res.locals.owner,'contact',String(req.params.id));res.sendStatus(204);});
 router.post('/memory',(req,res)=>res.status(201).json(db.create(res.locals.owner,'memory',memorySchema.parse(req.body))));router.delete('/memory/:id',(req,res)=>{db.remove(res.locals.owner,'memory',String(req.params.id));res.sendStatus(204);});
 router.post('/artifacts',express.raw({type:'application/octet-stream',limit:'20mb'}),async(req,res)=>{if(!Buffer.isBuffer(req.body))throw Error('Choose a file under 20 MB');const a=await saveAttachment(db,res.locals.owner,req.body,req.header('x-file-name')??'Attachment',req.header('x-file-type')??'');const {path,...safe}=a;res.status(201).json(safe);});
 router.get('/artifacts/:id/content',(req,res)=>{const a=db.get(res.locals.owner,'artifact',String(req.params.id));if(!a){res.sendStatus(404);return;}res.set('Content-Security-Policy',"default-src 'none'; sandbox");res.set('X-Content-Type-Options','nosniff');res.set('Content-Disposition',`inline; filename="${String(a.name).replace(/[^a-zA-Z0-9._ -]/g,'')}"`);if(a.path)res.type(a.mime).sendFile(a.path);else if(a.base64)res.type(a.mime).send(Buffer.from(a.base64,'base64'));else res.type('text/plain').send(a.text??JSON.stringify(a.data,null,2));});
 router.delete('/artifacts/:id',(req,res)=>{const a=db.get(res.locals.owner,'artifact',String(req.params.id));if(a?.path)try{unlinkSync(a.path);}catch{}db.remove(res.locals.owner,'artifact',String(req.params.id));res.sendStatus(204);});
 router.get('/events',(req,res)=>{res.set({'Content-Type':'text/event-stream',Connection:'keep-alive'});res.flushHeaders();let cursor=Number(req.header('last-event-id')??req.query.after??0)||0;const send=()=>{if(!current(req)){res.end();return;}for(const event of db.events(res.locals.owner,cursor)){res.write(`id: ${event.seq}\ndata: ${JSON.stringify(event)}\n\n`);cursor=event.seq;}res.write(': keepalive\n\n');};send();const timer=setInterval(send,1500);res.on('close',()=>clearInterval(timer));});
 router.post('/computers/:id/stop',async(req,res)=>{const r=db.get(res.locals.owner,'computer',String(req.params.id));if(!r){res.sendStatus(404);return;}q.cancel(res.locals.owner,r.runId);await browser.cancel(res.locals.owner,r.id);res.sendStatus(204);});
 router.post('/workflows',(req,res)=>{const v=z.object({name:z.string().min(1).max(100),task:z.string().min(1).max(12000),scheduledAt:z.string().datetime().optional()}).parse(req.body);res.status(201).json(db.create(res.locals.owner,'workflow',{...v,enabled:true}));});
 router.delete('/workflows/:id',(req,res)=>{db.remove(res.locals.owner,'workflow',String(req.params.id));res.sendStatus(204);});
 router.post('/workflows/:id/run',(req,res)=>{const w=db.get(res.locals.owner,'workflow',String(req.params.id));if(!w){res.sendStatus(404);return;}res.status(202).json(q.create(res.locals.owner,{task:w.task,context:{source:'workflow'}},req.header('idempotency-key')??''));void q.tick();});
 router.delete('/employee-data',async(req,res)=>{const owner=res.locals.owner;for(const r of db.list(owner,'run',-1))q.cancel(owner,r.id);for(const c of db.list(owner,'computer',-1))await browser.cancel(owner,c.id);for(const a of db.list(owner,'artifact',-1))if(a.path)try{unlinkSync(a.path);}catch{}rmSync(hermesHome(owner),{recursive:true,force:true});const u=await userResources(owner);u.notes=[];u.pendingNotifications=[];u.recentTasks=[];await saveStore();db.transaction(()=>{for(const table of ['records','events','dedupe','sessions'])db.sql.prepare(`DELETE FROM ${table} WHERE owner=?`).run(owner);});res.clearCookie('vc_session',{path:'/'}).sendStatus(204);});
 router.use((err:any,_req:Request,res:Response,_next:any)=>res.status(err instanceof z.ZodError?400:409).json({error:{message:err instanceof z.ZodError?'Please check the entered details.':redactText(String(err.message??'Unable to finish that request'))}}));app.use('/api',router);
 const timer=setInterval(()=>{try{for(const {owner,data:w} of db.all('workflow'))if(w.enabled&&w.scheduledAt&&Date.parse(w.scheduledAt)<=Date.now()){q.create(owner,{task:w.task,context:{source:'workflow'}},`schedule:${w.id}:${w.scheduledAt}`);db.put(owner,'workflow',{...w,enabled:false});}void q.tick().catch(()=>console.error(JSON.stringify({event:'employee.scheduler_error'})));void browser.cleanup().catch(()=>console.error(JSON.stringify({event:'employee.cleanup_error'})));}catch{console.error(JSON.stringify({event:'employee.scheduler_error'}));}},1000);timer.unref();
 return {db,q,tools,browser,current,cookieUser,stop:()=>{clearInterval(timer);q.stop();}};
}
